services:
  # Web service
  - type: web
    name: pdf-qa-app
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true
    disk:
      name: pdf-storage
      mountPath: /data
      sizeGB: 10

    # Instance size
    instanceType: basic
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 75

databases:
  # Vector database persistence
  - name: chromadb
    ipAllowList: []
    plan: starter
    region: oregon
    
staticAssets:
  - path: /static
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000